name: CI - MLflow Training Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Setup Miniconda + Langsung buat environment-nya di sini
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12.4"
          activate-environment: mlflow-env # Nama environment yang otomatis aktif
          environment-file: MLProject/conda.yaml # Membaca file conda.yaml kamu
          auto-activate-base: false

      # 2. Train model dengan MLflow
      - name: Train model with MLflow
        shell: bash -l {0} # <--- KRUSIAL: Membuka login-shell agar conda otomatis aktif
        run: |
          # Tidak perlu 'conda init' atau 'conda activate' lagi! 
          # Environment 'mlflow-env' sudah otomatis aktif berkat 'shell: bash -l {0}'
          mlflow run MLProject -P alpha=0.01 -P l1_ratio=0.5

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: flowers-model-${{ github.run_number }}
          path: |
            mlruns/
          retention-days: 30
